url: "https://www.typecheck.app" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Typecheck" # the name of your site, e.g. ACME Corp.

permalink: ':collection/:slug'

include:
  - _pages
  - _legal

collections:
  pages:
    permalink: /:slug/
  posts:
    permalink: /journal/:slug/
  legal:
    output: true

plugins:
  - jekyll-postcss-v2

postcss:
  cache: false
